using AutoFixture;
using AutoFixture.AutoNSubstitute;

namespace TUnit.AutoFixture.NSubstitute;

/// <summary>
/// Provides auto-generated test data using AutoFixture with NSubstitute auto-mocking.
/// Interfaces and abstract classes are automatically mocked using NSubstitute.
/// This attribute is compatible with xUnit's [AutoNSubstituteData] naming convention.
/// </summary>
/// <example>
/// Basic usage with auto-mocked interfaces:
/// <code>
/// [Test]
/// [AutoNSubstituteData]
/// public void TestMethod(IService service, string text, int number)
/// {
///     // IService is automatically mocked with NSubstitute
///     service.GetData().Returns("test");
///
///     // Primitives are generated by AutoFixture
///     Assert.IsNotNull(text);
///     Assert.AreNotEqual(0, number);
/// }
/// </code>
/// </example>
/// <example>
/// Usage with frozen mocks:
/// <code>
/// [Test]
/// [AutoNSubstituteData]
/// public void TestMethod([Frozen] IService service, Consumer consumer)
/// {
///     // The same IService mock is injected into both parameters
///     service.GetData().Returns("test");
///
///     var result = consumer.GetServiceData();
///
///     Assert.AreEqual("test", result);
///     service.Received(1).GetData();
/// }
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
public class AutoNSubstituteDataAttribute : AutoDataAttribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="AutoNSubstituteDataAttribute"/> class
    /// with NSubstitute auto-mocking enabled.
    /// </summary>
    public AutoNSubstituteDataAttribute()
        : base(CreateFixtureWithNSubstitute)
    {
    }

    /// <summary>
    /// Creates an AutoFixture instance configured with NSubstitute auto-mocking.
    /// </summary>
    /// <returns>
    /// An IFixture instance customized with AutoNSubstituteCustomization.
    /// </returns>
    private static IFixture CreateFixtureWithNSubstitute()
    {
        var fixture = new Fixture();
        fixture.Customize(new AutoNSubstituteCustomization
        {
            // Configure all mocks to use CallBase = false by default
            // This means mocks won't try to call base class implementations
            ConfigureMembers = false,
        });
        return fixture;
    }
}
