using AutoFixture;
using AutoFixture.AutoNSubstitute;

namespace TUnit.AutoFixture.NSubstitute;

/// <summary>
/// Combines explicit inline values with AutoFixture-generated parameters using NSubstitute auto-mocking.
/// Interfaces and abstract classes in the auto-generated portion are automatically mocked.
/// This attribute is compatible with xUnit's [InlineAutoNSubstituteData] naming convention.
/// </summary>
/// <example>
/// Basic usage:
/// <code>
/// [Test]
/// [InlineAutoNSubstituteData("explicit", 42)]
/// public void TestMethod(string explicitText, int explicitNumber, IService autoMock)
/// {
///     // First two parameters use explicit values
///     Assert.AreEqual("explicit", explicitText);
///     Assert.AreEqual(42, explicitNumber);
///
///     // IService is automatically mocked with NSubstitute
///     autoMock.GetData().Returns("test");
///     Assert.AreEqual("test", autoMock.GetData());
/// }
/// </code>
/// </example>
/// <example>
/// Multiple test cases:
/// <code>
/// [Test]
/// [InlineAutoNSubstituteData(100)]
/// [InlineAutoNSubstituteData(200)]
/// public void TestMethod(int explicitId, IRepository repo, Service sut)
/// {
///     // Creates 2 test cases with IDs 100 and 200
///     // IRepository is auto-mocked for each test case
///     repo.Get(explicitId).Returns(new Entity { Id = explicitId });
///
///     var result = sut.GetById(explicitId);
///
///     Assert.AreEqual(explicitId, result.Id);
/// }
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
public class InlineAutoNSubstituteDataAttribute : InlineAutoDataAttribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="InlineAutoNSubstituteDataAttribute"/> class
    /// with explicit values and NSubstitute auto-mocking for remaining parameters.
    /// </summary>
    /// <param name="values">
    /// The explicit values to use for the first N parameters.
    /// Remaining parameters will be auto-generated by AutoFixture with NSubstitute mocking.
    /// </param>
    public InlineAutoNSubstituteDataAttribute(params object?[] values)
        : base(CreateFixtureWithNSubstitute, values)
    {
    }

    /// <summary>
    /// Creates an AutoFixture instance configured with NSubstitute auto-mocking.
    /// </summary>
    /// <returns>
    /// An IFixture instance customized with AutoNSubstituteCustomization.
    /// </returns>
    private static IFixture CreateFixtureWithNSubstitute()
    {
        var fixture = new Fixture();
        fixture.Customize(new AutoNSubstituteCustomization
        {
            // Configure all mocks to use CallBase = false by default
            // This means mocks won't try to call base class implementations
            ConfigureMembers = false,
        });
        return fixture;
    }
}
