using AutoFixture;
using TUnit.AutoFixture.Internal;

namespace TUnit.AutoFixture;

/// <summary>
/// Provides auto-generated test data for all parameters using AutoFixture.
/// This attribute is compatible with xUnit's [AutoData] naming convention.
/// </summary>
/// <example>
/// Basic usage with primitive types:
/// <code>
/// [Test]
/// [AutoData]
/// public void TestMethod(string text, int number, bool flag)
/// {
///     // All parameters are automatically generated by AutoFixture
///     Assert.IsNotNull(text);
///     Assert.AreNotEqual(0, number);
/// }
/// </code>
/// </example>
/// <example>
/// Usage with complex types:
/// <code>
/// [Test]
/// [AutoData]
/// public void TestMethod(Person person, Address address)
/// {
///     // AutoFixture creates instances with populated properties
///     Assert.IsNotNull(person.Name);
///     Assert.IsNotNull(address.Street);
/// }
/// </code>
/// </example>
/// <example>
/// Usage with frozen dependencies:
/// <code>
/// [Test]
/// [AutoData]
/// public void TestMethod([Frozen] IService service, Consumer consumer)
/// {
///     // The same IService instance is injected into both parameters
///     Assert.AreSame(service, consumer.Service);
/// }
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
public class AutoDataAttribute : UntypedDataSourceGeneratorAttribute
{
    private readonly Lazy<IFixture> fixtureLazy;

    /// <summary>
    /// Initializes a new instance of the <see cref="AutoDataAttribute"/> class
    /// with the default AutoFixture configuration.
    /// </summary>
    public AutoDataAttribute()
        : this(() => new Fixture())
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AutoDataAttribute"/> class
    /// with a custom fixture factory. This constructor is protected to allow
    /// derived classes to provide custom AutoFixture configurations.
    /// </summary>
    /// <param name="fixtureFactory">
    /// A factory function that creates an IFixture instance.
    /// This is called lazily on first use.
    /// </param>
    protected AutoDataAttribute(Func<IFixture> fixtureFactory)
    {
        if (fixtureFactory is null)
        {
            throw new ArgumentNullException(nameof(fixtureFactory));
        }

        fixtureLazy = new Lazy<IFixture>(
            fixtureFactory,
            LazyThreadSafetyMode.PublicationOnly);
    }

    /// <summary>
    /// Gets the AutoFixture instance. This property is protected to allow
    /// derived classes (like InlineAutoDataAttribute) to access the fixture.
    /// </summary>
    protected IFixture Fixture => fixtureLazy.Value;

    /// <summary>
    /// Generates test data for the specified parameters using AutoFixture.
    /// This method is called by TUnit's source generator to provide test data.
    /// </summary>
    /// <param name="dataGeneratorMetadata">
    /// Metadata about the test method and parameters that need data generation.
    /// </param>
    /// <returns>
    /// An enumerable of functions that generate parameter arrays.
    /// Each function represents one test case (for this attribute, there's only one).
    /// </returns>
    protected override IEnumerable<Func<object?[]>> GenerateDataSources(DataGeneratorMetadata dataGeneratorMetadata)
    {
        if (dataGeneratorMetadata is null)
        {
            throw new ArgumentNullException(nameof(dataGeneratorMetadata));
        }

        return this.GenerateDataSourcesIterator(dataGeneratorMetadata);
    }

    private IEnumerable<Func<object?[]>> GenerateDataSourcesIterator(DataGeneratorMetadata dataGeneratorMetadata)
    {
        var parameters = dataGeneratorMetadata.MembersToGenerate;

        // If there are no parameters to generate, return empty array
        if (parameters.Length == 0)
        {
            yield return () => [];
            yield break;
        }

        // Return a single test case with all parameters auto-generated
        yield return () =>
        {
            var fixture = this.Fixture;
            var generator = new AutoFixtureDataGenerator(fixture);
            return generator.Generate(parameters);
        };
    }
}